### ISSUE TITLE
winx86 app crashed

### ISSUE THREAD

**Issue by mikowiec** [divVerent/aaaaxy#17]
Windows 7, x86, application crashed while run

```
>aaaaxy-windows-386.exe
2022/02/10 01:52:40 [INFO] could not find path for folder0/config.json: The handle is invalid.
2022/02/10 01:52:40 [INFO] requested logical scale factor: 0
2022/02/10 01:52:40 [INFO] device scale factor: 1
2022/02/10 01:52:40 [INFO] screen size: 1920x1200
2022/02/10 01:52:40 [INFO] max size: 1792x1072
2022/02/10 01:52:40 [INFO] max physical scale factors: 2.8, 2.977777777777778
2022/02/10 01:52:40 [INFO] requested physical scale factor: 2.8
2022/02/10 01:52:40 [INFO] chosen physical scale factor: 2
2022/02/10 01:52:40 [INFO] chosen logical pixel scale factor: 2
2022/02/10 01:52:40 [INFO] chosen window size: 1280x720
2022/02/10 01:52:40 [INFO] AAAAXY 1.1.112+20220207.1825.4f803d6a
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.cgocall(0x463b10, 0x26a73dc)
        runtime/cgocall.go:156 +0x58 fp=0x1456da48 sp=0x1456da30 pc=0x403958
syscall.Syscall6(0x7355451e, 0x6, 0x14689f58, 0xffffffff, 0x13c8b950, 0x464bc4, 0x0, 0x30000)
        runtime/syscall_windows.go:493 +0xbb fp=0x1456da64 sp=0x1456da48 pc=0x460e4b
golang.org/x/sys/windows.(*Proc).Call(0x1468d0e0, {0x13c8b968, 0x6, 0x6})
        golang.org/x/sys@v0.0.0-20220114195835-da31bd327af9/windows/dll_windows.go:180 +0x3bf fp=0x1456dae0 sp=0x1456da6
4 pc=0x5d2f3f
golang.org/x/sys/windows.(*LazyProc).Call(0x13c900d8, {0x13c8b968, 0x6, 0x6})
        golang.org/x/sys@v0.0.0-20220114195835-da31bd327af9/windows/dll_windows.go:348 +0x58 fp=0x1456db04 sp=0x1456dae0
 pc=0x5d3c58
github.com/hajimehoshi/oto/v2.waveOutOpen(0x13c8b950, 0x464bc4)
        github.com/hajimehoshi/oto/v2@v2.1.0-alpha.5/winmm_windows.go:136 +0xad fp=0x1456db40 sp=0x1456db04 pc=0x612b0d
github.com/hajimehoshi/oto/v2.newContext(0xac44, 0x2, 0x2)
        github.com/hajimehoshi/oto/v2@v2.1.0-alpha.5/driver_windows.go:111 +0x175 fp=0x1456db84 sp=0x1456db40 pc=0x61012
5
github.com/hajimehoshi/oto/v2.NewContext(0xac44, 0x2, 0x2)
        github.com/hajimehoshi/oto/v2@v2.1.0-alpha.5/driver.go:88 +0x35 fp=0x1456dbac sp=0x1456db84 pc=0x60fcb5
github.com/hajimehoshi/ebiten/v2/audio.newContext(...)
        github.com/hajimehoshi/ebiten/v2@v2.2.4/audio/player_notjs.go:25
github.com/hajimehoshi/ebiten/v2/audio.(*playerFactory).initContextIfNeeded(0x146a6840)
        github.com/hajimehoshi/ebiten/v2@v2.2.4/audio/player.go:102 +0x98 fp=0x1456dbdc sp=0x1456dbac pc=0x615518
github.com/hajimehoshi/ebiten/v2/audio.(*player).ensurePlayer(0x13c40450)
        github.com/hajimehoshi/ebiten/v2@v2.2.4/audio/player.go:116 +0x28 fp=0x1456dbf8 sp=0x1456dbdc pc=0x615618
github.com/hajimehoshi/ebiten/v2/audio.(*player).Play(0x13c40450)
        github.com/hajimehoshi/ebiten/v2@v2.2.4/audio/player.go:144 +0x63 fp=0x1456dc18 sp=0x1456dbf8 pc=0x6157f3
github.com/hajimehoshi/ebiten/v2/audio.(*Player).Play(...)
        github.com/hajimehoshi/ebiten/v2@v2.2.4/audio/audio.go:352
github.com/divVerent/aaaaxy/internal/audiowrap.Init()
        github.com/divVerent/aaaaxy/internal/audiowrap/player.go:80 +0x64 fp=0x1456dc30 sp=0x1456dc18 pc=0x6fcaa4
github.com/divVerent/aaaaxy/internal/aaaaxy.(*Game).InitStep.func2(0x13cf0288)
        github.com/divVerent/aaaaxy/internal/splash/splash.go:124 +0x1c fp=0x1456dc3c sp=0x1456dc30 pc=0x76186c
github.com/divVerent/aaaaxy/internal/splash.(*State).Enter(0x13cf0288, {0x7ff954, 0x12}, {0x806a03, 0x1a}, 0x1456dcd0)
        github.com/divVerent/aaaaxy/internal/splash/splash.go:109 +0x111 fp=0x1456dc8c sp=0x1456dc3c pc=0x690301
github.com/divVerent/aaaaxy/internal/aaaaxy.(*Game).InitStep(0x13cf0180)
        github.com/divVerent/aaaaxy/internal/aaaaxy/init.go:175 +0x176 fp=0x1456dd14 sp=0x1456dc8c pc=0x761246
github.com/divVerent/aaaaxy/internal/aaaaxy.(*Game).Update(0x13cf0180)
        github.com/divVerent/aaaaxy/internal/aaaaxy/game.go:138 +0xab fp=0x1456dd34 sp=0x1456dd14 pc=0x75d96b
github.com/hajimehoshi/ebiten/v2.(*imageDumper).update(0x13c9c720)
        github.com/hajimehoshi/ebiten/v2@v2.2.4/imagedumper_desktop.go:111 +0x42 fp=0x1456dde4 sp=0x1456dd34 pc=0x609502

github.com/hajimehoshi/ebiten/v2.(*imageDumperGame).Update(0x13c90840)
        github.com/hajimehoshi/ebiten/v2@v2.2.4/run.go:117 +0x80 fp=0x1456ddf4 sp=0x1456dde4 pc=0x60d580
github.com/hajimehoshi/ebiten/v2.(*uiContext).updateFrameImpl(0x26a6f20, 0x0)
        github.com/hajimehoshi/ebiten/v2@v2.2.4/uicontext.go:187 +0xab fp=0x1456de78 sp=0x1456ddf4 pc=0x60ee7b
github.com/hajimehoshi/ebiten/v2.(*uiContext).updateFrame(0x26a6f20, 0x0)
        github.com/hajimehoshi/ebiten/v2@v2.2.4/uicontext.go:159 +0x6f fp=0x1456de90 sp=0x1456de78 pc=0x60ed5f
github.com/hajimehoshi/ebiten/v2.(*uiContext).UpdateFrame(0x26a6f20)
        github.com/hajimehoshi/ebiten/v2@v2.2.4/uicontext.go:138 +0x2b fp=0x1456dea4 sp=0x1456de90 pc=0x60ec4b
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).loop(0x26a2e40)
        github.com/hajimehoshi/ebiten/v2@v2.2.4/internal/uidriver/glfw/ui.go:1103 +0x185 fp=0x1456dee4 sp=0x1456dea4 pc=
0x600a55
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).Run(0x26a2e40, {0x22d380c, 0x26a6f20})
        github.com/hajimehoshi/ebiten/v2@v2.2.4/internal/uidriver/glfw/run_singlethread.go:42 +0xfd fp=0x1456defc sp=0x1
456dee4 pc=0x5fcb2d
github.com/hajimehoshi/ebiten/v2.RunGame({0x22d26ec, 0x13cf0180})
        github.com/hajimehoshi/ebiten/v2@v2.2.4/run.go:160 +0xdf fp=0x1456df2c sp=0x1456defc pc=0x60d77f
main.runGame(0x13cf0180)
        github.com/divVerent/aaaaxy/main.go:51 +0x6a fp=0x1456df7c sp=0x1456df2c pc=0x7627ba
main.main()
        github.com/divVerent/aaaaxy/main.go:83 +0xe6 fp=0x1456dfc8 sp=0x1456df7c pc=0x762c26
runtime.main()
        runtime/proc.go:255 +0x23a fp=0x1456dff0 sp=0x1456dfc8 pc=0x438d4a
runtime.goexit()
        runtime/asm_386.s:1319 +0x1 fp=0x1456dff4 sp=0x1456dff0 pc=0x462da1

goroutine 20 [sync.Cond.Wait]:
sync.runtime_notifyListWait(0x1454cbe8, 0x0)
        runtime/sema.go:513 +0x175
sync.(*Cond).Wait(0x1454cbe0)
        sync/cond.go:56 +0xa0
github.com/hajimehoshi/oto/v2.(*players).wait(0x146a6870)
        github.com/hajimehoshi/oto/v2@v2.1.0-alpha.5/player_notjs.go:55 +0x6e
github.com/hajimehoshi/oto/v2.(*players).loop(0x146a6870)
        github.com/hajimehoshi/oto/v2@v2.1.0-alpha.5/player_notjs.go:62 +0x3b
created by github.com/hajimehoshi/oto/v2.newPlayers
        github.com/hajimehoshi/oto/v2@v2.1.0-alpha.5/player_notjs.go:37 +0xbf
eax     0x1
ebx     0x0
ecx     0x0
edx     0x73553af0
edi     0x2affa0
esi     0x3bb
ebp     0x0
esp     0x12fcd0
eip     0x0
eflags  0x10202
cs      0x1b
fs      0x3b
gs      0x0
```

**Comment by divVerent** [comment]
Thanks for the report!

First of all, if you launch from a cmd shell, you can pass -audio=false to turn off sound and see if the rest works.

The crashing function call is here: https://github.com/hajimehoshi/oto/blob/634126e062521f4b0a3cd6a46e4ec841b16ba6b2/winmm_windows.go#L136

As the program crashed in this way and not with a Go panic, we know that it did find the required DLL. The function receives:

```
  LPHWAVEOUT      phwo,
  UINT            uDeviceID,
  LPCWAVEFORMATEX pwfx,
  DWORD_PTR       dwCallback,
  DWORD_PTR       dwInstance,
  DWORD           fdwOpen
```

and the Go code passes an uintptr to an uintptr (this seems right), a waveMapper as a constant of value 0xffffffff (not sure if THAT is correct, maybe needs to be a typed constant on Go end), the WAVEFORMATEX struct (all well done in there), the callback pointer, zero as instance pointer (unused), and fdwOpen as an uintptr (not sure if that is right, either).

**Comment by divVerent** [comment]
Hm... the same x86 binary works fine on a Win10 system I have, and on WINE.

So it can't be THAT wrong. I wonder what this is then.

Does this crash happen every time?

**Comment by divVerent** [comment]
Gonna set up a Windows 7 VM to see if I can reproduce it. Not that this game is actually expected to run well in VMs (really needs OpenGL, but maybe I'll learn something about this crash).

**Comment by divVerent** [comment]
Next release, likely on Tuesday, will have the fix.

**Comment by divVerent** [comment]
I've done a build - can you try this download on your computer?

https://drive.google.com/file/d/1GeYOpYyVaJKgEOEQpJIze_1D5ljMuoKO/view?usp=sharing

Next week I will make a proper release - not expecting many changes versus this one. But this one contains some not very well tested new code for video recording, so you likely won't hit any of that; still would like to get that stable first before making it a proper release.
