### ISSUE TITLE
RunGame exited abnormally: VersionUnavailable: GLX: Failed to create context: BadValue (integer parameter out of range for operation)

### ISSUE THREAD

**Issue by Anonymous3-a** [divVerent/aaaaxy#243]
I recently updated the game, and it now isn't launching, instead it give this log (from terminal output, also I censored my name):

```
2023/07/25 16:46:31.242812 [INFO] requested logical scale factor: 0
2023/07/25 16:46:31.242820 [INFO] device scale factor: 1
2023/07/25 16:46:31.242841 [INFO] screen size: 1920x1080
2023/07/25 16:46:31.242843 [INFO] max size: 1792x952
2023/07/25 16:46:31.242847 [INFO] max physical scale factors: 2.8, 2.6444444444444444
2023/07/25 16:46:31.242851 [INFO] requested physical scale factor: 2.6444444444444444
2023/07/25 16:46:31.242853 [INFO] chosen physical scale factor: 2
2023/07/25 16:46:31.242856 [INFO] chosen logical pixel scale factor: 2
2023/07/25 16:46:31.242858 [INFO] chosen window size: 1280x720
2023/07/25 16:46:31.242861 [INFO] starting early initialization
2023/07/25 16:46:31.242867 [INFO] configs will be written to /home/[name]/.config/AAAAXY/*
2023/07/25 16:46:31.242873 [INFO] save games will be written to /home/[name]/.local/share/AAAAXY/*
2023/07/25 16:46:31.243530 [INFO] asset search path: [dat:aaaaxy.dat(.->/)]
2023/07/25 16:46:31.244940 [INFO] detected language English (not translating)
2023/07/25 16:46:31.245004 [INFO] font pinning coverage: 100%
2023/07/25 16:46:31.245012 [INFO] charset pinned:  !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\134]^_`abcdefghijklmnopqrstuvwxyz{|}~©¾àãéöπτ
2023/07/25 16:46:31.248000 [INFO] AAAAXY 1.4.39+20230725.3058.087fe586
2023/07/25 16:46:31.248007 [INFO] finished early initialization
goroutine 1 [running, locked to thread]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	runtime/debug/stack.go:16 +0x19
github.com/divVerent/aaaaxy/internal/log.Fatalf({0x5650540be21b, 0x1d}, {0xc00049df48, 0x1, 0x1})
	github.com/divVerent/aaaaxy/internal/log/log.go:101 +0x3c
main.main()
	github.com/divVerent/aaaaxy/main.go:125 +0x24d
2023/07/25 16:46:31.264193 [FATAL] RunGame exited abnormally: VersionUnavailable: GLX: Failed to create context: BadValue (integer parameter out of range for operation)
```

**Comment by Anonymous3-a** [comment]
Well, I rebooted and it was fixed?
